Enable build scans and automate graph updates in CI
This commit introduces two main changes to the GitHub Actions workflow:

1.  **Enable Build Scans:**
    *   Adds configuration to publish build scans to `gradle.com`.
    *   Includes agreement to the Gradle terms of service for build scans.
2.  **Automate Graph Updates:**
    *   Adds a step to update graphs using `./gradlew graphUpdate`.
    *   Adds a step to check if graphs have been updated.
    *   Prevents graph updates on forks and fails the build if graphs are not up-to-date.
    *   Automatically commits and pushes updated graph files (`**/README.md`) for pull requests.

Signed-off-by: Mahmooud Abdalhafeez <mahmoud99239@gmail.com>

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -47,6 +47,9 @@ jobs:
         uses: gradle/actions/setup-gradle@v4.4.2
         with:
           cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
+          build-scan-publish: true
+          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
+          build-scan-terms-of-use-agree: "yes"
 
       - name: Update web_client_id in secrets.defaults.properties
         run: |
@@ -111,6 +114,28 @@ jobs:
           file_pattern: '**/dependencies/*.txt'
           disable_globbing: true
           commit_message: "🤖 Updates baselines for Dependency Guard"
+
+      - name: Update Graphs
+        run: ./gradlew graphUpdate
+
+      - name: Check Graphs
+        id: graphs_verify
+        run: git add -- '**/README.md' && git diff --cached --quiet --exit-code -- '**/README.md'
+
+      - name: Prevent updating graphs if this is a fork
+        id: checkfork_graphs
+        continue-on-error: false
+        if: steps.graphs_verify.outcome == 'failure' && github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+            echo "::error::Check Graphs failed, please update graphs with: ./gradlew graphUpdate" && exit 1
+
+      - name: Push new graphs if available
+        if: steps.graphs_verify.outcome == 'failure' && github.event_name == 'pull_request'
+        uses: stefanzweifel/git-auto-commit-action@v5
+        with:
+          file_pattern: '**/README.md'
+          disable_globbing: true
+          commit_message: "🤖 Updates graphs"
 
       - name: Run local tests
         run: ./gradlew testDemoDebug :lint:test
